/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module vga_signals_4 (
    input clk,
    input rst,
    output reg hsync,
    output reg hblank,
    output reg vsync,
    output reg vblank,
    output reg [13:0] address
  );
  
  
  
  localparam WIDTH = 8'h80;
  
  localparam HEIGHT = 8'h80;
  
  localparam PIXEL_SIZE = 2'h3;
  
  localparam HVA_T = 10'h280;
  
  localparam HFP_T = 11'h290;
  
  localparam HSP_T = 12'h2f0;
  
  localparam HBP_T = 13'h0320;
  
  localparam VVA_T = 9'h1e0;
  
  localparam VFP_T = 10'h1ea;
  
  localparam VSP_T = 11'h1ec;
  
  localparam VBP_T = 12'h20d;
  
  localparam HMIN = 11'h080;
  
  localparam HMAX = 12'h200;
  
  localparam VMIN = 11'h030;
  
  localparam VMAX = 12'h1b0;
  
  localparam FREQ_DIV = 3'h4;
  
  integer hvisible;
  
  integer vvisible;
  
  localparam HVA_hstate = 2'd0;
  localparam HFP_hstate = 2'd1;
  localparam HSP_hstate = 2'd2;
  localparam HBP_hstate = 2'd3;
  
  reg [1:0] M_hstate_d, M_hstate_q = HVA_hstate;
  reg [11:0] M_hcounter_d, M_hcounter_q = 1'h0;
  localparam VVA_vstate = 2'd0;
  localparam VFP_vstate = 2'd1;
  localparam VSP_vstate = 2'd2;
  localparam VBP_vstate = 2'd3;
  
  reg [1:0] M_vstate_d, M_vstate_q = VVA_vstate;
  reg [9:0] M_vcounter_d, M_vcounter_q = 1'h0;
  
  always @* begin
    M_hstate_d = M_hstate_q;
    M_vstate_d = M_vstate_q;
    M_vcounter_d = M_vcounter_q;
    M_hcounter_d = M_hcounter_q;
    
    hvisible = M_hcounter_q >= 15'h01ff && M_hcounter_q < 16'h07ff;
    vvisible = M_vcounter_q >= 11'h030 && M_vcounter_q < 12'h1b0;
    hsync = 1'h1;
    vsync = 1'h0;
    hblank = !hvisible;
    vblank = !vvisible;
    if (hvisible && vvisible) begin
      address[7+6-:7] = (M_vcounter_q - 11'h030) / 2'h3;
      address[0+6-:7] = (M_hcounter_q - 15'h01ff) / 5'h0c;
    end else begin
      address = 1'h0;
    end
    M_hcounter_d = M_hcounter_q + 1'h1;
    
    case (M_hstate_q)
      HVA_hstate: begin
        if (M_hcounter_q == 14'h09ff) begin
          M_hstate_d = HFP_hstate;
        end
      end
      HFP_hstate: begin
        if (M_hcounter_q == 15'h0a3f) begin
          M_hstate_d = HSP_hstate;
        end
      end
      HSP_hstate: begin
        hsync = 1'h0;
        if (M_hcounter_q == 16'h0bbf) begin
          M_hstate_d = HBP_hstate;
        end
      end
      HBP_hstate: begin
        if (M_hcounter_q == 17'h00c7f) begin
          M_hstate_d = HVA_hstate;
          M_hcounter_d = 1'h0;
          M_vcounter_d = M_vcounter_q + 1'h1;
        end
      end
    endcase
    
    case (M_vstate_q)
      VVA_vstate: begin
        if (M_vcounter_q == 9'h1e0) begin
          M_vstate_d = VFP_vstate;
        end
      end
      VFP_vstate: begin
        if (M_vcounter_q == 10'h1ea) begin
          M_vstate_d = VSP_vstate;
        end
      end
      VSP_vstate: begin
        vsync = 1'h1;
        if (M_vcounter_q == 11'h1ec) begin
          M_vstate_d = VBP_vstate;
        end
      end
      VBP_vstate: begin
        if (M_vcounter_q == 12'h20d) begin
          M_vstate_d = VVA_vstate;
          M_vcounter_d = 1'h0;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_hcounter_q <= 1'h0;
      M_vcounter_q <= 1'h0;
      M_hstate_q <= 1'h0;
      M_vstate_q <= 1'h0;
    end else begin
      M_hcounter_q <= M_hcounter_d;
      M_vcounter_q <= M_vcounter_d;
      M_hstate_q <= M_hstate_d;
      M_vstate_q <= M_vstate_d;
    end
  end
  
endmodule
