/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     COLORS = COLORS
*/
module vga_ramdac_7 (
    input clk,
    input rst,
    input en,
    input [3:0] vram_data,
    output reg [5:0] rgb
  );
  
  localparam COLORS = 5'h10;
  
  
  localparam PALETTE = 96'hfb698b33ce31fea564252040;
  
  reg [5:0] M_this_rgb_d, M_this_rgb_q = 1'h0;
  
  always @* begin
    M_this_rgb_d = M_this_rgb_q;
    
    rgb = M_this_rgb_q;
    if (en) begin
      M_this_rgb_d = PALETTE[(vram_data)*6+5-:6];
    end else begin
      M_this_rgb_d = 6'h00;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_this_rgb_q <= 1'h0;
    end else begin
      M_this_rgb_q <= M_this_rgb_d;
    end
  end
  
endmodule
