/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module vga_signals_6 (
    input clk,
    input rst,
    output reg pixel_clk,
    output reg line_clk,
    output reg hsync,
    output reg vsync,
    output reg hblank,
    output reg vblank,
    output reg [13:0] address
  );
  
  
  
  localparam WIDTH = 8'h80;
  
  localparam HEIGHT = 8'h80;
  
  localparam HPIXEL_SIZE = 2'h3;
  
  localparam VPIXEL_SIZE = 2'h3;
  
  localparam HVA_T = 10'h280;
  
  localparam HFP_T = 12'h28f;
  
  localparam HSP_T = 14'h02ee;
  
  localparam HBP_T = 16'h031d;
  
  localparam VVA_T = 9'h1e0;
  
  localparam VFP_T = 10'h1ea;
  
  localparam VSP_T = 11'h1ec;
  
  localparam VBP_T = 12'h20d;
  
  localparam HMIN_T = 11'h080;
  
  localparam HMAX_T = 12'h200;
  
  localparam VMIN_T = 11'h030;
  
  localparam VMAX_T = 12'h1b0;
  
  reg hvisibility;
  
  reg vvisibility;
  
  reg lvisibility;
  
  reg [6:0] haddress;
  
  reg [6:0] vaddress;
  
  reg [11:0] M_hcounter_d, M_hcounter_q = 1'h0;
  reg [9:0] M_vcounter_d, M_vcounter_q = 1'h0;
  reg [1:0] M_pcounter_d, M_pcounter_q = 1'h0;
  reg [1:0] M_lcounter_d, M_lcounter_q = 1'h0;
  
  always @* begin
    hvisibility = M_hcounter_q >= 11'h080 && M_hcounter_q < 12'h200 ? 1'h1 : 1'h0;
    vvisibility = M_vcounter_q >= 11'h030 && M_vcounter_q < 12'h1b0 ? 1'h1 : 1'h0;
    lvisibility = M_vcounter_q >= 12'h02d && M_vcounter_q < 13'h01ad ? 1'h1 : 1'h0;
    hsync = M_hcounter_q >= 12'h28f && M_hcounter_q < 14'h02ee ? 1'h0 : 1'h1;
    vsync = M_vcounter_q >= 10'h1ea && M_vcounter_q < 11'h1ec ? 1'h0 : 1'h1;
    hblank = ~hvisibility;
    vblank = ~vvisibility;
    pixel_clk = M_pcounter_q == 1'h0 ? 1'h1 : 1'h0;
    line_clk = lvisibility && M_lcounter_q == 1'h0 ? 1'h1 : 1'h0;
    if (hvisibility && vvisibility) begin
      haddress = (M_hcounter_q - 11'h080) / 2'h3;
      vaddress = (M_vcounter_q - 11'h030) / 2'h3;
    end else begin
      haddress = 7'h00;
      vaddress = 7'h00;
    end
    address = {vaddress, haddress};
  end
  
  always @* begin
    M_vcounter_d = M_vcounter_q;
    M_hcounter_d = M_hcounter_q;
    M_pcounter_d = M_pcounter_q;
    M_lcounter_d = M_lcounter_q;
    
    if (M_hcounter_q < 16'h031d) begin
      M_hcounter_d = M_hcounter_q + 1'h1;
      if (M_pcounter_q < 3'h2) begin
        M_pcounter_d = M_pcounter_q + 1'h1;
      end else begin
        M_pcounter_d = 1'h0;
      end
    end else begin
      M_hcounter_d = 1'h0;
      M_pcounter_d = 1'h0;
      if (M_vcounter_q < 12'h20d) begin
        M_vcounter_d = M_vcounter_q + 1'h1;
        if (M_lcounter_q < 3'h2) begin
          M_lcounter_d = M_lcounter_q + 1'h1;
        end else begin
          M_lcounter_d = 1'h0;
        end
      end else begin
        M_vcounter_d = 1'h0;
        M_lcounter_d = 1'h0;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_hcounter_q <= 1'h0;
      M_vcounter_q <= 1'h0;
      M_pcounter_q <= 1'h0;
      M_lcounter_q <= 1'h0;
    end else begin
      M_hcounter_q <= M_hcounter_d;
      M_vcounter_q <= M_vcounter_d;
      M_pcounter_q <= M_pcounter_d;
      M_lcounter_q <= M_lcounter_d;
    end
  end
  
endmodule
