from miniish.pyco.constants import *

BANNER = """
miniish 0.1
(c) 2022-24 romuald rousseau

"""

PROMPT = "> "

MAX_BUFFERS = 8

COLOR_CONS_BG = BLACK
COLOR_CONS_FG = WHITE
COLOR_MAIN_BG = DARK_GRAY
COLOR_MAIN_FG = LIGHT_GRAY
COLOR_STAT_BG = RED
COLOR_STAT_FG = DARK_PURPLE
COLOR_CURSOR  = RED

SYNTAX_TOKEN = LIGHT_GRAY
SYNTAX_SYMBOL = WHITE
SYNTAX_NUMBER = BLUE
SYNTAX_STRING = BLUE
SYNTAX_KEYWORD1 = GREEN
SYNTAX_KEYWORD2 = PINK
SYNTAX_COMMENT = INDIGO
