M48
; DRILL file {KiCad 7.0.3} date Fri 19 May 2023 11:21:26 PM +08
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-19T23:21:26+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X0.0Y0.0
X0.0Y-6.1024
X6.2205Y-0.1969
X6.2205Y-6.1024
T2
X4.4394Y-0.7547
T0
M30
